/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LibraryFindDuplicatesImport } from './routes/library/find-duplicates'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LibraryFindDuplicatesRoute = LibraryFindDuplicatesImport.update({
  path: '/library/find-duplicates',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/library/find-duplicates': {
      id: '/library/find-duplicates'
      path: '/library/find-duplicates'
      fullPath: '/library/find-duplicates'
      preLoaderRoute: typeof LibraryFindDuplicatesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/library/find-duplicates': typeof LibraryFindDuplicatesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/library/find-duplicates': typeof LibraryFindDuplicatesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/library/find-duplicates': typeof LibraryFindDuplicatesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library/find-duplicates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library/find-duplicates'
  id: '__root__' | '/' | '/library/find-duplicates'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LibraryFindDuplicatesRoute: typeof LibraryFindDuplicatesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LibraryFindDuplicatesRoute: LibraryFindDuplicatesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/library/find-duplicates"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/library/find-duplicates": {
      "filePath": "library/find-duplicates.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
